/**
 * @license
 * Copyright 2022-2023 Project CHIP Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { Globals } from "../../../src/model/index.js";

export const typeMap: { [name: string]: keyof typeof Globals} = {
    BOOLEAN: "bool",
    BITMAP8: "map8",
    BITMAP16: "map16",
    BITMAP24: "map24",
    BITMAP32: "map32",
    BITMAP64: "map64",
    INT8U: "uint8",
    INT16U: "uint16",
    INT24U: "uint24",
    INT32U: "uint32",
    INT40U: "uint40",
    INT48U: "uint48",
    INT56U: "uint56",
    INT64U: "uint64",
    INT8S: "int8",
    INT16S: "int16",
    INT24S: "int24",
    INT32S: "int32",
    INT40S: "int40",
    INT48S: "int48",
    INT56S: "int56",
    INT64S: "int64",
    ENUM8: "enum8",
    ENUM16: "enum16",
    SINGLE: "single",
    DOUBLE: "double",
    OCTET_STRING: "octstr",
    CHAR_STRING: "string",
    LONG_OCTET_STRING: "octstr",
    LONG_CHAR_STRING: "string",
    ARRAY: "list",
    STRUCT: "struct",
    TOD: "tod",
    DATE: "date",
    UTC: "utc",
    EPOCH_US: "epochUs",
    EPOCH_S: "epochS",
    SYSTIME_US: "systimeUs",
    PERCENT: "percent",
    PERCENT100THS: "percent100ths",
    CLUSTER_ID: "clusterId",
    ATTRIB_ID: "attributeId",
    FIELD_ID: "fieldId",
    EVENT_ID: "eventId",
    COMMAND_ID: "commandId",
    ACTION_ID: "actionId",
    TRANS_ID: "transactionId",
    NODE_ID: "nodeId",
    VENDOR_ID: "vendorId",
    DEVTYPE_ID: "deviceTypeId",
    FABRIC_ID: "fabricId",
    GROUP_ID: "groupId",
    STATUS: "status",
    DATA_VER: "dataVer",
    EVENT_NO: "eventNo",
    ENDPOINT_NO: "endpointNo",
    FABRIC_IDX: "fabricIdx",
    IPADR: "ipadr",
    IPV4ADR: "ipv4adr",
    IPV6ADR: "ipv6adr",
    IPV6PRE: "ipv6pre",
    HWADR: "hwadr"
};
