/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { ElementTag } from "#common/ElementTag.js";
import { InternalError } from "#general";
import type { Model } from "#models/Model.js";
import { MetadataConflictError } from "../errors.js";
import type { ClassDecoration } from "./ClassDecoration.js";

const TYPED_TAGS = new Set([ElementTag.Attribute, ElementTag.Field, ElementTag.Command, ElementTag.Event]);

/**
 * Base class for decoration applied to classes and fields.
 *
 * We use the term "decoration" to describe the metadata generated by decorators.  This base class handles functionality
 * common to both classes and fields.
 */
export abstract class Decoration {
    abstract name?: string;
    #kind?: Model.ConcreteType;
    #type?: Model;
    #response?: Model;
    #id?: number;

    get kind() {
        return this.#kind;
    }

    set kind(kind: Model.ConcreteType | undefined) {
        if (this.#kind) {
            if (this.#kind === kind) {
                return;
            }

            throw new MetadataConflictError(
                `Cannot define ${this.name} as ${kind?.Tag} because it is already defined as ${this.#kind}`,
            );
        }

        if (!this.#validateKindAndType(kind, this.#type)) {
            throw new MetadataConflictError(
                `Cannot assign ${this.name} as ${kind?.Tag} because it is already ${this.#type?.tag}`,
            );
        }

        this.#kind = kind;
    }

    get id() {
        return this.#id;
    }

    set id(id: number | undefined) {
        if (this.#id !== undefined) {
            if (this.#id === id) {
                return;
            }

            throw new MetadataConflictError(
                `Cannot define ${this.name} as #${id} because it is already defined as #${this.#id}`,
            );
        }

        this.#id = id;
    }

    get type(): Model | undefined {
        return this.#type;
    }

    set type(type: Model.Source | undefined) {
        const newType = type && Decoration.modelOf(type);
        const currentType = this.type;
        if (currentType) {
            if (newType !== currentType) {
                throw new MetadataConflictError(
                    `Cannot define ${this.name} as ${newType?.name} because it is already defined as ${currentType.name}`,
                );
            }
            return;
        }

        if (!this.#validateKindAndType(this.#kind, newType)) {
            throw new MetadataConflictError(
                `Cannot define ${this.name} as ${newType?.tag} because it is already defined as ${this.#kind?.Tag}`,
            );
        }

        this.#type = newType;
    }

    get response(): Model | undefined {
        return this.#response;
    }

    set response(response: Model.Source | undefined) {
        const newResponse = response && Decoration.modelOf(response);
        const currentResponse = this.response;
        if (currentResponse) {
            if (newResponse !== currentResponse) {
                throw new MetadataConflictError(
                    `Cannot set ${this.name} response type as ${newResponse?.name} because it is already ${currentResponse.name}`,
                );
            }
            return;
        }

        this.#response = newResponse;
    }

    /**
     * Ensure that a {@link kind} model can extend a {@link type} instance.
     *
     * They're considered compatible if:
     *
     *   * Either is undefined
     *
     *   * They have the same tag
     *
     *   * {@link kind} represents a value and {@link type} is a datatype
     */
    #validateKindAndType(kind: Model.ConcreteType | undefined, type: Model | undefined) {
        if (kind === undefined || type === undefined || type.tag === kind.Tag) {
            return true;
        }

        return type.tag === ElementTag.Datatype && TYPED_TAGS.has(kind.Tag);
    }
}

export namespace Decoration {
    /**
     * Access the {@link Decoration} of a {@link DecoratorContext}.
     */
    export function of(context: DecoratorContext) {
        const classDecoration = classDecorationOf(context);
        if (context.kind === "class") {
            return classDecoration;
        }
        return classDecoration.fieldFor(context.name);
    }

    /**
     * Access the {@link ClassDecoration} of a constructor or decorator context.
     */
    // eslint-disable-next-line prefer-const
    export let classDecorationOf = (_source: ClassDecoration.Source): ClassDecoration => {
        // This should be replaced by ClassDecoration
        throw new InternalError(`Class decoration lookup not installed`);
    };

    /**
     * Access the {@link Model} of a {@link Source}.
     */
    export function modelOf(source: Model.Source) {
        if ("tag" in source) {
            return source;
        }
        return classDecorationOf(source).model;
    }
}
