/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { InternalError } from "#general";
import type { Model } from "#models/Model.js";
import type { ClassDecoration } from "./ClassDecoration.js";

/**
 * Base class for decoration applied to classes and fields.
 *
 * We use the term "decoration" to describe the metadata generated by decorators.  This base class handles functionality
 * common to both classes and fields.
 */
export abstract class Decoration {
    #model?: Model;

    /**
     * Obtain the {@link Model} defined by this metadata.
     */
    get model() {
        if (this.#model === undefined) {
            this.#model = this.createModel();
        }
        return this.#model;
    }

    /**
     * Replace the model.
     *
     * Children will move but other properties are lost.
     */
    set model(model: Model) {
        if (this.#model !== undefined) {
            model.children.push(...this.#model.children);
        }
        this.#model = model;
    }

    /**
     * The model's {@link Model.Type}.
     *
     * Field decorators operate prior to class decorators, so we may need to transition the model to a new type when the
     * class is decorated.  This is slightly lossy so type-specific decoration should always occur after assigning kind.
     */
    get modelType() {
        return this.model.constructor as Model.ConcreteType;
    }

    set modelType(type: Model.ConcreteType) {
        if (this.#model === undefined) {
            this.#model = this.createModel(type);
            return;
        }

        if (this.#model instanceof type) {
            return;
        }

        // Detach original model
        const original = this.#model as Model;
        const { parent } = original;
        original.parent = undefined;

        // Create replacement
        const replacement = new type({
            name: original.name,
            id: original.id,
            type: original.type,
            parent,
            operationalBase: original.operationalBase,
            children: original.children,
        });

        if ("quality" in original && "quality" in replacement) {
            replacement.quality = original.quality;
        }
    }

    protected abstract createModel(type?: Model.ConcreteType): Model;
}

export namespace Decoration {
    /**
     * Access the {@link Decoration} of a {@link DecoratorContext}.
     */
    export function of(context: DecoratorContext) {
        const classDecoration = classDecorationOf(context);
        if (context.kind === "class") {
            return classDecoration;
        }
        return classDecoration.fieldFor(context.name);
    }

    /**
     * Access the {@link ClassDecoration} of a constructor or decorator context.
     */
    // eslint-disable-next-line prefer-const
    export let classDecorationOf = (_source: ClassDecoration.Source): ClassDecoration => {
        // This should be replaced by ClassDecoration
        throw new InternalError(`Class decoration lookup not installed`);
    };

    /**
     * Access the {@link Model} of a {@link Source}.
     */
    export function modelOf(source: Model.Source) {
        if ("tag" in source) {
            return source;
        }
        return classDecorationOf(source).model;
    }
}
