#!/bin/bash

# Loads build targets into a local image tagged "chip/<target>"

set -e

if ! docker buildx inspect matter.js-chip > /dev/null 2>&1; then
    docker buildx create --name matter.js-chip
fi

TARGET=$1
if [ -z "${TARGET}" ]; then
    echo "Target name required" >&2
    exit 1
fi
shift

docker buildx build . \
    --builder matter.js-chip \
    --load \
    -t "chip/${TARGET}" \
    --target "${TARGET}" \
    --label org.opencontainers.image.revision=$(git rev-parse HEAD) \
    --platform linux/amd64 \
    $*
