#!/bin/bash

THISDIR=$(dirname -- "${BASH_SOURCE[0]}")
GIT_ROOT=$(realpath "${THISDIR}/../../..")

docker run \
    -it \
    --rm \
    --workdir / \
    --security-opt apparmor:unconfined \
    --platform linux/amd64 \
    ghcr.io/matter-js/chip \
    "$@"
