/**
 * @license
 * Copyright 2022-2023 Project CHIP Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*** THIS FILE IS GENERATED, DO NOT EDIT ***/

import { Matter } from "../Matter.js";

Matter.children.push({
    tag: "cluster", id: 0x0004, name: "Groups",
    classification: "endpoint", description: "Groups",
    children: [
        {
            tag: "attribute", id: 0x0000, name: "NameSupport",
            access: "R V", conformance: "M", constraint: "desc", default: 0, quality: "F", type: "map8",
            details: "This attribute provides legacy, read-only access to whether the Group " +
                     "Names feature is supported. The most significant bit, bit 7, SHALL be " +
                     "equal to bit 0 of the FeatureMap attribute. All other bits SHALL be 0",
            xref: { document: "cluster", section: "1.3.6.1" }
        },

        {
            tag: "attribute", id: 0x0000, name: "GroupNameSupport",
            conformance: "M", type: "map8"
        },

        {
            tag: "command", id: 0x0000, name: "AddGroup",
            access: "R F M", conformance: "M", direction: "request", response: "AddGroupResponse",
            details: "The AddGroup command allows a client to add group membership in a " +
                     "particular group for the server endpoint",
            xref: { document: "cluster", section: "1.3.7.1" },
            children: [
                {
                    tag: "datatype", name: "GroupId",
                    conformance: "M", type: "group-id"
                },

                {
                    tag: "datatype", name: "GroupName",
                    conformance: "M", type: "string"
                }
            ]
        },

        {
            tag: "command", id: 0x0001, name: "ViewGroupResponse",
            conformance: "M", direction: "response",
            details: "The ViewGroupResponse command is sent by the Groups cluster server in " +
                     "response to a ViewGroup command",
            xref: { document: "cluster", section: "1.3.7.8" },
            children: [
                {
                    tag: "datatype", name: "Status",
                    conformance: "M", type: "enum8"
                },

                {
                    tag: "datatype", name: "GroupId",
                    conformance: "M", type: "group-id"
                },

                {
                    tag: "datatype", name: "GroupName",
                    conformance: "M", type: "string"
                }
            ]
        },

        {
            tag: "command", id: 0x0002, name: "GetGroupMembershipResponse",
            conformance: "M", direction: "response",
            details: "The GetGroupMembershipResponse command is sent by the Groups cluster " +
                     "server in response to a GetGroupMembership command",
            xref: { document: "cluster", section: "1.3.7.9" },
            children: [
                {
                    tag: "datatype", name: "Capacity",
                    conformance: "M", quality: "X", type: "uint8"
                },

                {
                    tag: "datatype", name: "GroupList",
                    conformance: "M", type: "group-id"
                }
            ]
        },

        {
            tag: "command", id: 0x0003, name: "RemoveGroupResponse",
            conformance: "M", direction: "response",
            details: "The RemoveGroupResponse command is generated by the server in response" +
                     " to the receipt of a RemoveGroup command",
            xref: { document: "cluster", section: "1.3.7.10" },
            children: [
                {
                    tag: "datatype", name: "Status",
                    conformance: "M", type: "enum8"
                },

                {
                    tag: "datatype", name: "GroupId",
                    conformance: "M", type: "group-id"
                }
            ]
        },

        {
            tag: "command", id: 0x0004, name: "RemoveAllGroups",
            access: "R F M", conformance: "M", direction: "request", response: "status",
            details: "The RemoveAllGroups command allows a client to direct the server to " +
                     "remove all group associations for the server endpoint",
            xref: { document: "cluster", section: "1.3.7.5" }
        },

        {
            tag: "command", id: 0x0005, name: "AddGroupIfIdentifying",
            access: "R F M", conformance: "M", direction: "request", response: "status",
            details: "The AddGroupIfIdentifying command allows a client to add group " +
                     "membership in a particular group for the server endpoint, on condition" +
                     " that the endpoint is identifying itself. Identifying functionality is" +
                     " controlled using the Identify cluster, (see Identify",
            xref: { document: "cluster", section: "1.3.7.6" },
            children: [
                {
                    tag: "datatype", name: "GroupId",
                    conformance: "M", type: "group-id"
                },

                {
                    tag: "datatype", name: "GroupName",
                    conformance: "M", type: "string"
                }
            ]
        },

        {
            tag: "command", id: 0x0000, name: "AddGroupResponse",
            conformance: "M", direction: "response",
            details: "The AddGroupResponse is sent by the Groups cluster server in response " +
                     "to an AddGroup command. The AddGroupResponse command SHALL have the " +
                     "following data fields",
            xref: { document: "cluster", section: "1.3.7.7" },
            children: [
                {
                    tag: "datatype", name: "Status",
                    conformance: "M", type: "enum8"
                },

                {
                    tag: "datatype", name: "GroupId",
                    conformance: "M", type: "group-id"
                }
            ]
        },

        {
            tag: "datatype", name: "GroupsFeature",
            conformance: "M", type: "map32",
            children: [
                {
                    tag: "datatype", id: 0x0001, name: "GroupNames",
                    conformance: "M"
                }
            ]
        }
    ]
});
