/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*** THIS FILE IS GENERATED, DO NOT EDIT ***/

import { AreaNamespaceNs } from "#index.js";

AreaNamespaceNs.patch({
    details: "The tags contained in this namespace may be used in any domain or context, to indicate an " +
        "association with an indoor or outdoor area of a home.",
    xref: "namespace§13",

    children: [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "Also known as Restroom" },
        undefined,
        undefined,
        { description: "A small room typically used for storage" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A small, comfortable room for individual activities such as work or hobbies" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A bathroom directly accessible from a bedroom" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "Also known as Guest Restroom" },
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A cozy room containing a fireplace or other point heat source" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A space used to remove soiled garments prior to entering the domicile proper" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "AKA a larder, a place where food is stored" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A utility space for cleaning dishes and laundry" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "An informal space meant to be 'cozy', 'snug', relaxed, meant to share with family or friends" },
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        { description: "A room dedicated to a toilet; a water closet / WC" }
    ]
});
