/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*** THIS FILE IS GENERATED, DO NOT EDIT ***/

import { MatterDefinition } from "../MatterDefinition.js";
import {
    SemanticNamespaceElement as SemanticNamespace,
    SemanticTagElement as SemanticTag
} from "../../elements/index.js";

export const AreaNamespaceNs = SemanticNamespace(
    { id: 0x10, name: "AreaNamespace" },
    SemanticTag({ id: 0x0, name: "Aisle" }),
    SemanticTag({ id: 0x1, name: "Attic" }),
    SemanticTag({ id: 0x2, name: "Back Door" }),
    SemanticTag({ id: 0x3, name: "Back Yard" }),
    SemanticTag({ id: 0x4, name: "Balcony" }),
    SemanticTag({ id: 0x5, name: "Ballroom" }),
    SemanticTag({ id: 0x6, name: "Bathroom" }),
    SemanticTag({ id: 0x7, name: "Bedroom" }),
    SemanticTag({ id: 0x8, name: "Border" }),
    SemanticTag({ id: 0x9, name: "Boxroom" }),
    SemanticTag({ id: 0xa, name: "Breakfast Room" }),
    SemanticTag({ id: 0xb, name: "Carport" }),
    SemanticTag({ id: 0xc, name: "Cellar" }),
    SemanticTag({ id: 0xd, name: "Cloakroom" }),
    SemanticTag({ id: 0xe, name: "Closet" }),
    SemanticTag({ id: 0xf, name: "Conservatory" }),
    SemanticTag({ id: 0x10, name: "Corridor" }),
    SemanticTag({ id: 0x11, name: "Craft Room" }),
    SemanticTag({ id: 0x12, name: "Cupboard" }),
    SemanticTag({ id: 0x13, name: "Deck" }),
    SemanticTag({ id: 0x14, name: "Den" }),
    SemanticTag({ id: 0x15, name: "Dining" }),
    SemanticTag({ id: 0x16, name: "Drawing Room" }),
    SemanticTag({ id: 0x17, name: "Dressing Room" }),
    SemanticTag({ id: 0x18, name: "Driveway" }),
    SemanticTag({ id: 0x19, name: "Elevator" }),
    SemanticTag({ id: 0x1a, name: "Ensuite" }),
    SemanticTag({ id: 0x1b, name: "Entrance" }),
    SemanticTag({ id: 0x1c, name: "Entryway" }),
    SemanticTag({ id: 0x1d, name: "Family Room" }),
    SemanticTag({ id: 0x1e, name: "Foyer" }),
    SemanticTag({ id: 0x1f, name: "Front Door" }),
    SemanticTag({ id: 0x20, name: "Front Yard" }),
    SemanticTag({ id: 0x21, name: "Game Room" }),
    SemanticTag({ id: 0x22, name: "Garage" }),
    SemanticTag({ id: 0x23, name: "Garage Door" }),
    SemanticTag({ id: 0x24, name: "Garden" }),
    SemanticTag({ id: 0x25, name: "Garden Door" }),
    SemanticTag({ id: 0x26, name: "Guest Bathroom" }),
    SemanticTag({ id: 0x27, name: "Guest Bedroom" }),
    SemanticTag({ id: 0x28, name: "Guest Room" }),
    SemanticTag({ id: 0x29, name: "Gym" }),
    SemanticTag({ id: 0x2a, name: "Hallway" }),
    SemanticTag({ id: 0x2b, name: "Hearth Room" }),
    SemanticTag({ id: 0x2c, name: "Kids Room" }),
    SemanticTag({ id: 0x2d, name: "Kids Bedroom" }),
    SemanticTag({ id: 0x2e, name: "Kitchen" }),
    SemanticTag({ id: 0x2f, name: "Laundry Room" }),
    SemanticTag({ id: 0x30, name: "Lawn" }),
    SemanticTag({ id: 0x31, name: "Library" }),
    SemanticTag({ id: 0x32, name: "Living Room" }),
    SemanticTag({ id: 0x33, name: "Lounge" }),
    SemanticTag({ id: 0x34, name: "Media/TV Room" }),
    SemanticTag({ id: 0x35, name: "Mud Room" }),
    SemanticTag({ id: 0x36, name: "Music Room" }),
    SemanticTag({ id: 0x37, name: "Nursery" }),
    SemanticTag({ id: 0x38, name: "Office" }),
    SemanticTag({ id: 0x39, name: "Outdoor Kitchen" }),
    SemanticTag({ id: 0x3a, name: "Outside" }),
    SemanticTag({ id: 0x3b, name: "Pantry" }),
    SemanticTag({ id: 0x3c, name: "Parking Lot" }),
    SemanticTag({ id: 0x3d, name: "Parlor" }),
    SemanticTag({ id: 0x3e, name: "Patio" }),
    SemanticTag({ id: 0x3f, name: "Play Room" }),
    SemanticTag({ id: 0x40, name: "Pool Room" }),
    SemanticTag({ id: 0x41, name: "Porch" }),
    SemanticTag({ id: 0x42, name: "Primary Bathroom" }),
    SemanticTag({ id: 0x43, name: "Primary Bedroom" }),
    SemanticTag({ id: 0x44, name: "Ramp" }),
    SemanticTag({ id: 0x45, name: "Reception Room" }),
    SemanticTag({ id: 0x46, name: "Recreation Room" }),
    SemanticTag({ id: 0x47, name: "Roof" }),
    SemanticTag({ id: 0x48, name: "Sauna" }),
    SemanticTag({ id: 0x49, name: "Scullery" }),
    SemanticTag({ id: 0x4a, name: "Sewing Room" }),
    SemanticTag({ id: 0x4b, name: "Shed" }),
    SemanticTag({ id: 0x4c, name: "Side Door" }),
    SemanticTag({ id: 0x4d, name: "Side Yard" }),
    SemanticTag({ id: 0x4e, name: "Sitting Room" }),
    SemanticTag({ id: 0x4f, name: "Snug" }),
    SemanticTag({ id: 0x50, name: "Spa" }),
    SemanticTag({ id: 0x51, name: "Staircase" }),
    SemanticTag({ id: 0x52, name: "Steam Room" }),
    SemanticTag({ id: 0x53, name: "Storage Room" }),
    SemanticTag({ id: 0x54, name: "Studio" }),
    SemanticTag({ id: 0x55, name: "Study" }),
    SemanticTag({ id: 0x56, name: "Sun Room" }),
    SemanticTag({ id: 0x57, name: "Swimming Pool" }),
    SemanticTag({ id: 0x58, name: "Terrace" }),
    SemanticTag({ id: 0x59, name: "Toilet" }),
    SemanticTag({ id: 0x5a, name: "Utility Room" }),
    SemanticTag({ id: 0x5b, name: "Ward" }),
    SemanticTag({ id: 0x5c, name: "Workshop" })
);

MatterDefinition.children.push(AreaNamespaceNs);
