/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { MissingMetadataError } from "#decoration/errors.js";
import { InternalError } from "#general";
import type { Model } from "#models/Model.js";
import type { ClassSemantics } from "./ClassSemantics.js";

/**
 * Base class for decoration applied to classes and fields.
 *
 * We use the term "decoration" to describe the metadata generated by decorators.  This base class handles functionality
 * common to both classes and fields.
 */
export abstract class Semantics {
    #localModel?: Model;

    /**
     * The {@link Model} defined by local decoration, if any.
     */
    get localModel() {
        return this.#localModel;
    }

    /**
     * Set the model.
     *
     * If you replace the model, children will move but other properties are lost.
     */
    set mutableModel(model: Model) {
        if (this.#localModel !== undefined) {
            if (model.isFrozen) {
                model = model.extend();
            }
            model.children.push(...this.#localModel.children);
        }
        this.#localModel = model;
    }

    /**
     * Obtain a model unconditionally for mutation purposes.
     */
    get mutableModel() {
        if (this.#localModel === undefined) {
            this.#localModel = this.createModel();
        } else if (this.#localModel.isFrozen) {
            this.#localModel = this.#localModel.extend();
        }
        return this.#localModel;
    }

    /**
     * The model's {@link Model.Type}.
     *
     * Field decorators operate prior to class decorators, so we may need to transition the model to a new type when the
     * class is decorated.  This is slightly lossy so type-specific decoration should always occur after assigning kind.
     */
    get modelType(): Model.Type | undefined {
        if (this.#localModel === undefined) {
            return;
        }
        return this.mutableModel.constructor as Model.ConcreteType;
    }

    set modelType(type: Model.ConcreteType) {
        if (this.#localModel === undefined) {
            this.#localModel = this.createModel(type);
            return;
        }

        if (this.#localModel instanceof type) {
            return;
        }

        // Detach original model
        const original = this.#localModel as Model;
        const { parent } = original;
        original.parent = undefined;

        // Create replacement
        const replacement = new type({
            name: original.name,
            id: original.id,
            type: original.type,
            parent,
            operationalBase: original.operationalBase,
            children: original.children,
        });

        if ("quality" in original && "quality" in replacement) {
            replacement.quality = original.quality;
        }

        this.#localModel = replacement;
    }

    protected abstract createModel(type?: Model.ConcreteType): Model;
}

export namespace Semantics {
    /**
     * Access the {@link Semantics} of a {@link DecoratorContext}.
     */
    export function of(context: DecoratorContext) {
        const classSemantics = classOf(context);
        if (context.kind === "class") {
            return classSemantics;
        }
        return classSemantics.fieldFor(context.name);
    }

    /**
     * Access the {@link ClassSemantics} of a constructor or decorator context.
     */
    // eslint-disable-next-line prefer-const
    export let classOf = (_source: ClassSemantics.Source): ClassSemantics => {
        // This should be replaced by ClassSemantics
        throw new InternalError(`Class decoration lookup not installed`);
    };

    /**
     * Access the {@link Model} of a {@link Source}.
     */
    export function modelOf(source: Model.Source) {
        if ("tag" in source) {
            return source;
        }
        const semantics = classOf(source);

        const model = semantics.semanticModel;

        if (model && (model.constructor as Model.ConcreteType).requiresId) {
            throw new MissingMetadataError(`Model ${source.name} is missing mandatory numeric ID`);
        }

        return model;
    }
}
